### ISSUE TITLE
ClassFactory.GetDynamicClass() does not appear to be thread safe

### ISSUE THREAD

**Issue by mobilebilly** [kahanu/System.Linq.Dynamic#50]
The `classes.Add(signature, type)` method call is placed within a ReaderLock (which is a shared lock),:
```
public Type GetDynamicClass(IEnumerable<DynamicProperty> properties)
        {
            rwLock.AcquireReaderLock(Timeout.Infinite);
            try
            {
                Signature signature = new Signature(properties);
                Type type;
                if (!classes.TryGetValue(signature, out type))
                {
                    type = CreateDynamicClass(signature.properties);
                    classes.Add(signature, type);
                }
                return type;
            }
            finally
            {
                rwLock.ReleaseReaderLock();
            }
        }
```

if multiple threads are accessing the GetDynamicClass method simultaneously, the following runtime exception might occur:

```
"An element with the same key already exists."

at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add) at System.Linq.Dynamic.ClassFactory.GetDynamicClass(IEnumerable1 properties)
at System.Linq.Dynamic.DynamicExpression.CreateClass(IEnumerable1 properties) at System.Linq.Dynamic.ExpressionParser.ParseNew() at System.Linq.Dynamic.ExpressionParser.ParseIdentifier() at System.Linq.Dynamic.ExpressionParser.ParsePrimaryStart() at System.Linq.Dynamic.ExpressionParser.ParsePrimary() at System.Linq.Dynamic.ExpressionParser.ParseUnary() at System.Linq.Dynamic.ExpressionParser.ParseMultiplicative() at System.Linq.Dynamic.ExpressionParser.ParseAdditive() at System.Linq.Dynamic.ExpressionParser.ParseComparison() at System.Linq.Dynamic.ExpressionParser.ParseLogicalAnd() at System.Linq.Dynamic.ExpressionParser.ParseLogicalOr() at System.Linq.Dynamic.ExpressionParser.ParseExpression() at System.Linq.Dynamic.ExpressionParser.Parse(Type resultType) at System.Linq.Dynamic.DynamicExpression.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values) at System.Linq.Dynamic.DynamicExpression.ParseLambda(Type itType, Type resultType, String expression, Object[] values) at System.Linq.Dynamic.DynamicQueryable.Select(IQueryable source, String selector, Object[] values) at EntityFramework.Batch.SqlServerBatchRunner.GetSelectSql[TEntity](ObjectQuery1 query, EntityMap entityMap, DbCommand command)
```

The error _might_ happen when multiple threads are making call to something like below
System.Linq.Dynamic.Select(“new …”)

The problem is mentioned in the links below:
https://github.com/loresoft/EntityFramework.Extended/issues/76

http://stackoverflow.com/questions/7156181/system-linq-dynamic-selectnew-does-not-appear-to-be-thread-safe

A pull request (#48) is submitted to fix the issue by placing the `classes.Add(signature, type)` method call within a writer lock (which is an exclusive lock)

**Comment by ryanvgates** [comment]
Pull request #48 is related to this issue.

**Comment by ryanvgates** [comment]
Closing this issue after merging in the changeset.
